apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: hello
          image: adish869/flask_proj:latest
          ports:
          - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: myapp
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-lb
  labels:
    app: myapp
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
     app: myapp
